server:
  port: 8099

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/auth/realms/test
          audiences: api
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customer/**
        - id: book
          uri: lb://BOOK
          predicates:
            - Path=/api/v1/book/**
        - id: search
          uri: lb://SEARCH
          predicates:
            - Path=/api/v1/search/**
        - id: auth
          uri: http://localhost:8180
          predicates:
            - Path=/auth/**

logger:
  enabled: true

logtrace:
  enabled: true
  before-message-prefix: '['
  after-message-prefix: '['

logging:
  level:
    com.dm4nk: info

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
