server:
  port: 8099

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customer/**
        - id: ban
          uri: lb://BAN
          predicates:
            - Path=/api/v1/ban-check/**
        - id: search
          uri: lb://SEARCH
          predicates:
            - Path=/api/v1/search/**
