server:
  port: 8097

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: search

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

