server:
  port: 8097

spring:
  threads:
    virtual:
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: search
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      client-id: ${spring.application.name}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:8081
    consumer:
      group-id: ${spring.application.name}
      keyDeserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      valueDeserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: io.confluent.kafka.serializers.KafkaAvroDeserializer
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true

elasticsearch:
  host-and-port: localhost:9200
  customer-index-name: searchservice-customer

logger:
  enabled: true

logtrace:
  enabled: true
  before-message-prefix: '['
  after-message-prefix: '['

logging:
  level:
    com.dm4nk: info

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
