server:
  port: 8091

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: book
  datasource:
    password: anime_the_best
    url: jdbc:postgresql://localhost:5431/book
    username: dm4nk
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    open-in-view: false

logger:
  enabled: true

logtrace:
  enabled: true
  before-message-prefix: '['
  after-message-prefix: '['

logging:
  level:
    com.dm4nk: info

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 0.9
