server:
  port: 8091

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: book
  datasource:
    password: anime_the_best
    url: jdbc:postgresql://localhost:5431/book
    username: dm4nk
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    open-in-view: false
