{
 "title": "REST Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "service", "label": "service", "query": "customer" }
  ]
 },
 "panels": [
  { "title": "Common Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rate 5** errors",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{status=~'5..', uri=~'^/api/v1/(.)*$', service=\"$service\"} [$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5** htt codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum by (status, method, uri) (increase(http_server_requests_seconds_count{status=~'5..', uri=~'^/api/v1/(.)*$', service=\"$service\"} [$__range]))",
     "legendFormat": "{{status}} {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "2** http count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{status=~'2..', uri=~'^/api/v1/(.)*$', service=\"$service\"} [$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "2** htt codes (increase)",
   "type": "timeseries",
   "description": "Все запросы с кодом 2**",
   "gridPos": { "h": 9, "w": 9, "x": 4, "y": 9 },
   "targets": [
    {
     "expr": "sum by (status, method, uri) (increase(http_server_requests_seconds_count{status=~'2..', uri=~'^/api/v1/(.)*$', service=\"$service\"} [$__range]))",
     "legendFormat": "{{status}} {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "2** htt codes (count)",
   "type": "timeseries",
   "description": "Все запросы с кодом 2**",
   "gridPos": { "h": 9, "w": 9, "x": 13, "y": 9 },
   "targets": [
    {
     "expr": "sum by (status, method, uri) (http_server_requests_seconds_count{status=~'2..', uri=~'^/api/v1/(.)*$', service=\"$service\"})",
     "legendFormat": "{{status}} {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "4** http count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{status=~'4..', uri=~'^/api/v1/(.)*$', service=\"$service\"} [$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4** http codes (increase)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 4, "y": 18 },
   "targets": [
    {
     "expr": "sum by (status, method, uri) (increase(http_server_requests_seconds_count{status=~'4..', uri=~'^/api/v1/(.)*$', service=\"$service\"} [$__range]))",
     "legendFormat": "{{status}} {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "4** http codes (count)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 13, "y": 18 },
   "targets": [
    {
     "expr": "sum by (status, method, uri) (http_server_requests_seconds_count{status=~'4..', uri=~'^/api/v1/(.)*$', service=\"$service\"})",
     "legendFormat": "{{status}} {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Rate 2** codes",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status, uri, method) (increase(http_server_requests_seconds_count{status=~'2..', uri=~'^/api/v1/(.)*$', service=\"$service\"} [$__range]))",
     "legendFormat": "{{status}} {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Rate 401 codes",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status, method, uri, service) (increase(http_server_requests_seconds_count{status=~'401', uri=~'^/api/v1/(.)*$', service=\"$service\"}[$__range]))",
     "legendFormat": "{{status}} {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Rate 4** codes",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status, method, uri, service) (increase(http_server_requests_seconds_count{status=~'4..', uri=~'^/api/v1/(.)*$', service=\"$service\"}[$__range]))",
     "legendFormat": "{{status}} {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Rate 422 codes",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status, method, uri, service) (increase(http_server_requests_seconds_count{status=~'422', uri=~'^/api/v1/(.)*$', service=\"$service\"}[$__range]))",
     "legendFormat": "{{status}} {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Rate 404 codes",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status, method, uri, service) (increase(http_server_requests_seconds_count{status=~'404', uri=~'^/api/v1/(.)*$', service=\"$service\"}[$__range]))",
     "legendFormat": "{{status}} {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Rate 409 codes",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status, method, uri, service) (increase(http_server_requests_seconds_count{status=~'409', uri=~'^/api/v1/(.)*$', service=\"$service\"}[$__range]))",
     "legendFormat": "{{status}} {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Rate 400 codes",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status, method, uri, service) (increase(http_server_requests_seconds_count{status=~'400', uri=~'^/api/v1/(.)*$', service=\"$service\"}[$__range]))",
     "legendFormat": "{{status}} {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Rate 2** codes for 24h",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (increase(http_server_requests_seconds_count{status=~'2..', uri=~'^/api/v1/(.)*$', service=\"$service\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate 4** codes 24h",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (increase(http_server_requests_seconds_count{status=~'4..', uri=~'^/api/v1/(.)*$', service=\"$service\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "NT Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Rate any codes",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (uri, method) (increase(http_server_requests_seconds_count{uri=~'^/api/v1/(.)*$', service=\"$service\"} [$__range]))",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Requests in period",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 8, "x": 9, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc((sum(increase(http_server_requests_seconds_count{uri=~'^/api/v1/(.)*$', service=\"$service\"} [$__range])) by (uri, method)))",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "RPS summary",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(rate(http_server_requests_seconds_count{uri=~'^/api/v1/(.)*$', service=\"$service\"} [1m])) by (uri, method))",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Вызов методов репозиториев",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 73 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (method, repository) (increase(spring_data_repository_invocations_seconds_count{service=\"$service\"} [$__range])))",
     "legendFormat": "{{repository}}.{{method}}"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 9, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_max{uri=~'^/api/v1/(.)*$', service=\"$service\"} [1m])) by (uri, method)",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "RPS peaks",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 73 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=~'^/api/v1/(.)*$', service=\"$service\"} [1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HicariCP Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 9, "y": 84 },
   "targets": [
    {
     "expr": "hikaricp_connections_active{service=\"$service\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pinned threads",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 84 },
   "targets": [
    {
     "expr": "sum(rate(thread_pinning_seconds_count{service=\"$service\"} [1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}