spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

logger:
  enabled: true

logtrace:
  enabled: true
  before-message-prefix: '['
  after-message-prefix: '['

logging:
  level:
    com.dm4nk: info

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    enabled: true
    sampling:
      probability: 1
