apiVersion: apps/v1
kind: Deployment
metadata:
  name: ban
  labels:
    app: ban
spec:
  replicas: 1
  template:
    metadata:
      name: ban
      labels:
        app: ban
    spec:
      containers:
        - name: ban
          image: dm4nk/ban:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
      restartPolicy: Always
  selector:
    matchLabels:
      app: ban
