clients.customer.url=http://localhost:8080
clients.search.url=http://localhost:8097
clients.book.url=http://localhost:8091
clients.book.path=/api/v1/book
clients.recorder.url=http://localhost:8094
clients.recorder.path=/api/v1/actions
